[package]
name = "root"
version = "0.1.0"
edition = "2024"

[dependencies]
brane_weaver = { path = "../../brane_weaver/" }
proc_brane_weaver = { path = "../../proc_brane_weaver/" }
cargodeps = { path = "../cargodeps" } 

[features]
default = ["static_modules"]

# enables static linking of game engine modules
# disable to allow hot-reloading to work
static_modules = []
